# Generated by Django 4.1.1 on 2022-09-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["priority", "-created_date"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="task",
            new_name="body",
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("hight", "High priority"),
                    ("middle", "Middle priority"),
                    ("low", "Low priority"),
                ],
                default="middle",
                max_length=20,
            ),
        ),
    ]
