# Generated by Django 4.1.1 on 2022-09-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_options_rename_task_task_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("High priority", "Hight"),
                    ("Middle priority", "middle"),
                    ("Low priority", "low"),
                ],
                default="middle",
                max_length=20,
            ),
        ),
    ]
