# Generated by Django 4.1.1 on 2022-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("hight", "High priority"),
                    ("middle", "Middle priority"),
                    ("low", "Low priority"),
                ],
                default="middle",
                max_length=20,
            ),
        ),
    ]
